### ISSUE TITLE
Not running in parallel

### ISSUE THREAD

**Issue by PathriK** [Siva-Keerthi/SampleTestNG#2]
The test method seems to be getting invoked only once. Guess even though the same class is included in the test set twice, only once it gets executed.

Lets add two test classes with 2 test methods each and try it out

**Comment by sivakumarthiyas** [comment]
Working on it.

**Comment by sivakumarthiyas** [comment]
Removed @afterClass and @beforeClass and added after/before method in the Base test. Created new class and verified, it is working fine.
